# Generated by Django 5.1.2 on 2025-11-25 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Doctor'), (2, 'Reception'), (3, 'Other'), (0, 'Admin')], null=True),
        ),
    ]
