# Generated by Django 5.1.6 on 2026-04-26 10:54

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('created_at', django_jalali.db.models.jDateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaffType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', django_jalali.db.models.jDateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount', models.IntegerField(default=0.0)),
                ('daily_used', models.IntegerField(blank=True, null=True)),
                ('created_at', django_jalali.db.models.jDateField(auto_now_add=True)),
                ('updated_at', django_jalali.db.models.jDateField(auto_now=True)),
                ('jalali_month', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('date', django_jalali.db.models.jDateField(auto_now_add=True)),
                ('jalali_month', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('fee', models.DecimalField(blank=True, decimal_places=1, max_digits=12, null=True)),
                ('patient_type', models.CharField(max_length=255)),
                ('created_at', django_jalali.db.models.jDateField(auto_now_add=True)),
                ('jalali_month', models.CharField(blank=True, max_length=20)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.categorytype')),
            ],
        ),
        migrations.CreateModel(
            name='Pharmaceutical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_used', models.IntegerField(default=1)),
                ('copy', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', django_jalali.db.models.jDateField(auto_now_add=True)),
                ('updated_at', django_jalali.db.models.jDateField(auto_now=True)),
                ('jalali_month', models.CharField(blank=True, max_length=20)),
                ('doctor_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee')),
                ('patient_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PharmaceuticalDrug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_used', models.IntegerField(default=1)),
                ('created_at', django_jalali.db.models.jDateField(auto_now_add=True)),
                ('jalali_month', models.CharField(blank=True, max_length=20)),
                ('pharmaceutical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pharmaceutical')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.stock')),
            ],
        ),
        migrations.AddField(
            model_name='pharmaceutical',
            name='drugs',
            field=models.ManyToManyField(through='core.PharmaceuticalDrug', to='core.stock'),
        ),
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('refer_to', models.CharField(max_length=300)),
                ('date', django_jalali.db.models.jDateField(auto_now_add=True)),
                ('jalali_month', models.CharField(blank=True, max_length=20)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.patient')),
                ('test_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.testtype')),
            ],
        ),
    ]
