# Generated by Django 5.1.2 on 2024-12-11 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_name_staff_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='received_money',
        ),
    ]
