# Generated by Django 5.1.2 on 2025-11-22 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_dailyexpensepharmacy_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmaceutical',
            name='amount_used',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pharmaceutical',
            name='drug',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.stock'),
            preserve_default=False,
        ),
    ]
