# Generated by Django 5.1.2 on 2025-11-22 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_pharmaceutical_amount_used_pharmaceutical_drug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmaceutical',
            name='drug',
        ),
        migrations.AddField(
            model_name='pharmaceutical',
            name='drug',
            field=models.ManyToManyField(to='core.stock'),
        ),
    ]
