# Generated by Django 5.1.2 on 2025-11-22 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_pharmaceutical_drug_pharmaceutical_drug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmaceutical',
            name='drug',
        ),
        migrations.CreateModel(
            name='PharmaceuticalDrug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_used', models.IntegerField(default=1)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.stock')),
                ('pharmaceutical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pharmaceutical')),
            ],
        ),
        migrations.AddField(
            model_name='pharmaceutical',
            name='drugs',
            field=models.ManyToManyField(through='core.PharmaceuticalDrug', to='core.stock'),
        ),
    ]
