# Generated by Django 5.1.2 on 2025-11-22 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_pharmaceutical_drug_pharmaceuticaldrug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='daily_used',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
