# Generated by Django 5.1.2 on 2025-12-02 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_testtype_labtest'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='labtest',
            name='refer_to',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
