# Generated by Django 5.1.2 on 2024-12-11 18:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_pharmaceutical_patient_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='present_day',
        ),
        migrations.AddField(
            model_name='staff',
            name='email',
            field=models.EmailField(default='noemail@domain.com', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='last_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='staff',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Doctor'), (2, 'Reception'), (0, 'Other')], null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='stared_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staff',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.categorytype'),
        ),
    ]
